version: "3.7"
   
services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=dataschema
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rHya2Lm4fT
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/dataschema
    ports:
      - "8000:8000"
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3.8.11

  celery:
    build: .
    command: celery -A dataschema worker -l INFO
    restart: on-failure
    volumes:
      - .:/dataschema
    depends_on:
      - db
      - rabbitmq
